---
- name: Configure unbound upstart defaults
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - Reload init scripts
    - Restart unbound
  with_items:
    - { src: "unbound-upstart-default.j2", dest: "/etc/default/unbound" }
  tags:
    - unbound-config
    - unbound-init
    - upstart-init

- name: Drop unbound main configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - Reload init scripts
    - Restart unbound
  with_items:
    - { src: "unbound.conf.j2", dest: "/etc/unbound/unbound.conf" }
  tags:
    - unbound-config

- name: Drop unbound local configurations
  template:
    src: "{{ item.template }}.j2"
    dest: "{{ unbound_conf_dir }}/{{ (item.priority|default('50')|string).rjust(3, '0') }}-{{ item.template }}"
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload init scripts
    - Restart unbound
  with_items: unbound_configuration_templates
  tags:
    - unbound-config

- name: Drop unbound extra records
  template:
    src: "extra_records.conf.j2"
    dest: "{{ unbound_conf_dir }}/{{ (item.priority|default('50')|string).rjust(3, '0') }}-{{ item.name }}.conf"
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload init scripts
    - Restart unbound
  with_items: unbound_records
  tags:
    - unbound-config

- name: Start unbound and add to boot services
  service:
   name: "unbound"
   enabled: yes
   state: started
  tags:
    - upstart-init
    - unbound-init

- name: Flush handlers
  meta: flush_handlers
